import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart' show rootBundle;

import 'local_store.dart';

/// The standalone build: a whole farm on the tablet, with no server.
///
/// There is no API deployment and no production database yet, so this
/// build ships its own data. `assets/demo/snapshot.json` is generated by
/// `backend/app/export_demo_snapshot.py`, which seeds a throwaway
/// database with the backend's own demo dataset, starts the real API
/// in-process and records the genuine response of every endpoint the
/// tablet reads. That matters: the dataset is correct by construction, in
/// the exact shape the server would send, rather than fixture JSON that
/// drifts the first time a schema changes.
///
/// On first sign-in the snapshot is loaded into the same `cache` table
/// the offline layer already uses, so every screen reads it through the
/// normal [ApiClient] path with no special-casing. Writes then edit that
/// data in place — an animal added here really is added, and is still
/// there after a restart.
///
/// Nothing here is a security boundary. The credential is checked on the
/// device because there is no server to ask; it exists so someone can
/// open the app and walk through the farm, not to protect anything.
class DemoMode {
  DemoMode._();

  static const String username = 'ali';
  static const String password = 'ali123';

  static const String _assetPath = 'assets/demo/snapshot.json';
  static const String _accountKey = '__demo_account__';

  /// This store holds the demo farm. Set once, when the data is first
  /// loaded, and deliberately *not* cleared by signing out — the local
  /// data is the farm, not a cached copy of one.
  static const String metaSeeded = 'standalone_demo';

  /// A demo session is open. Cleared on sign-out, so the login screen
  /// comes back; signing in again resumes the same farm rather than
  /// reloading the bundled one over whatever has been entered since.
  static const String metaSession = 'standalone_session';

  /// True when the entered credentials are the demo account's. Trimmed
  /// and case-insensitive on the username — a farmer typing into a
  /// tablet keyboard should not be defeated by a capital A.
  static bool matches(String user, String pass) =>
      user.trim().toLowerCase() == username && pass == password;

  /// Loads the bundled farm into [store] and returns the profile to sign
  /// in as, or null if the asset is missing or unreadable.
  ///
  /// Re-seeding is skipped when the store already holds demo data, so a
  /// second sign-in does not wipe out what the user has entered since.
  static Future<Map<String, dynamic>?> activate(LocalStore store, {bool reset = false}) async {
    if (!store.available) return null;

    final alreadySeeded = await store.meta(metaSeeded) == 'true';
    if (alreadySeeded && !reset) {
      final existing = await store.metaJson(_profileKey);
      if (existing != null) {
        await store.setMeta(metaSession, 'true');
        return existing;
      }
    }

    final Map<String, dynamic> snapshot;
    try {
      snapshot = jsonDecode(await rootBundle.loadString(_assetPath)) as Map<String, dynamic>;
    } catch (e) {
      debugPrint('DemoMode: could not load $_assetPath ($e)');
      return null;
    }

    final account = snapshot[_accountKey];
    final profile = account is Map<String, dynamic> ? account['user'] : null;
    if (profile is! Map<String, dynamic>) {
      debugPrint('DemoMode: snapshot has no demo account profile');
      return null;
    }

    if (reset) await store.clearCache();
    for (final entry in snapshot.entries) {
      if (entry.key == _accountKey) continue;
      await store.writeCache(entry.key, entry.value);
    }
    await store.setMeta(metaSeeded, 'true');
    await store.setMeta(metaSession, 'true');
    await store.setMetaJson(_profileKey, profile);
    return profile;
  }

  /// True when a demo session is open — what decides, at launch, whether
  /// to go straight into the farm or show the login screen.
  static Future<bool> hasOpenSession(LocalStore? store) async =>
      store != null && store.available && await store.meta(metaSession) == 'true';

  static Future<Map<String, dynamic>?> storedProfile(LocalStore store) => store.metaJson(_profileKey);

  /// Signs out without touching the farm data.
  static Future<void> endSession(LocalStore? store) async => store?.setMeta(metaSession, null);

  /// Wipes the demo farm and reloads it from the bundled snapshot —
  /// "Reset demo data" in Settings, for handing the tablet to the next
  /// person with a clean farm.
  static Future<Map<String, dynamic>?> reset(LocalStore store) => activate(store, reset: true);

  static const String _profileKey = 'demo_profile';
}
