"""mouneh module

Revision ID: 2826c438f6dd
Revises: 4870e2312357
Create Date: 2026-08-25 06:02:20.767950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2826c438f6dd'
down_revision: Union[str, None] = '4870e2312357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_products', sa.Integer(), nullable=True),
    sa.Column('activated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'module_code', name='uq_module_license_farm_module')
    )
    op.create_table('mouneh_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouneh_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('output_unit', sa.String(length=30), nullable=False),
    sa.Column('custom_output_unit_label', sa.String(length=50), nullable=True),
    sa.Column('default_batch_size', sa.Float(), nullable=False),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('warehouse_rules', sa.Text(), nullable=True),
    sa.Column('low_stock_threshold', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('wholesale_price', sa.Float(), nullable=True),
    sa.Column('target_margin_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('license_required', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'category', 'name', name='uq_mouneh_product_farm_category_name')
    )
    op.create_table('mouneh_recipes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('basis_quantity', sa.Float(), nullable=False),
    sa.Column('basis_unit', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['mouneh_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_version_id', sa.String(length=36), nullable=False),
    sa.Column('batch_code', sa.String(length=50), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=False),
    sa.Column('actual_output_qty', sa.Float(), nullable=True),
    sa.Column('waste_qty', sa.Float(), nullable=False),
    sa.Column('damaged_qty', sa.Float(), nullable=False),
    sa.Column('quality_status', sa.String(length=20), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('warehouse_location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('planned_unit_cost', sa.Float(), nullable=True),
    sa.Column('planned_total_cost', sa.Float(), nullable=True),
    sa.Column('actual_unit_cost', sa.Float(), nullable=True),
    sa.Column('actual_total_cost', sa.Float(), nullable=True),
    sa.Column('labor_hours', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['mouneh_products.id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['mouneh_recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_id', 'batch_code', name='uq_batch_farm_code')
    )
    op.create_table('raw_materials',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('default_unit_cost', sa.Float(), nullable=False),
    sa.Column('stock_tracking_enabled', sa.Boolean(), nullable=False),
    sa.Column('current_stock', sa.Float(), nullable=False),
    sa.Column('loss_percent_default', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_input_consumptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('planned_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_components',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('cost_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('calculation_method', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('allocation_basis', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['mouneh_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finished_goods_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_location', sa.String(length=200), nullable=True),
    sa.Column('quantity_produced', sa.Float(), nullable=False),
    sa.Column('quantity_available', sa.Float(), nullable=False),
    sa.Column('quantity_reserved', sa.Float(), nullable=False),
    sa.Column('quantity_sold', sa.Float(), nullable=False),
    sa.Column('quantity_expired', sa.Float(), nullable=False),
    sa.Column('quantity_damaged', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['mouneh_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouneh_recipe_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('material_id', sa.String(length=36), nullable=False),
    sa.Column('material_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('loss_percent', sa.Float(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['raw_materials.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['mouneh_recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mouneh_sale_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('farm_id', sa.String(length=36), nullable=False),
    sa.Column('sale_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('finished_goods_stock_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=False),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sold_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['production_batches.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['finished_goods_stock_id'], ['finished_goods_stock.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['mouneh_products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mouneh_sale_lines')
    op.drop_table('mouneh_recipe_items')
    op.drop_table('finished_goods_stock')
    op.drop_table('cost_components')
    op.drop_table('batch_input_consumptions')
    op.drop_table('raw_materials')
    op.drop_table('production_batches')
    op.drop_table('mouneh_recipes')
    op.drop_table('mouneh_products')
    op.drop_table('mouneh_events')
    op.drop_table('module_licenses')
    # ### end Alembic commands ###
