"""user department field

Revision ID: c57f1a0ec3cb
Revises: 056144584d12
Create Date: 2026-08-26 13:02:27.300831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57f1a0ec3cb'
down_revision: Union[str, None] = '056144584d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
